# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd240fbfca3b1bceb63b807c5b32552957a1643b6fcecd71d107f24bd5e750ebd6c1e6ac338b0800a119e5b8829d778b54655c2d5ff059de0bc408a764d34f4d

test:
  secret_key_base: 4a08b32c72855ac678075b930722cb9b8364c3f989c57f3ff545854ba76650b890b3abe01533b51279fcfa1347a6f80ad5b5a51badd9f034abdb09dc145f78c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
