# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7947e2d4d850b2288fe4ca9cda1ff162edfca6861f300746c9e6cb0d6f316a4f53adf00f53090b5712360fbf276b8107df87817b6c78755fa815e3dd1a94371d

test:
  secret_key_base: a1795ad5667358d93d0b9a95587459d972e504c6b17866c8137b191b488085812dbca2c34f9bddd1f4c2ed14fcd7923f59b8d909ca38caf79a9c7eebdbd0a332

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
